---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: oraclelinux
    image: oraclelinux:8
    pre_build_image: true
    command: "dnf install python3"
  - name: ubuntu
    image: ubuntu:latest
    pre_build_image: true
    command: "apt update && apt install -y python3.9"
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /var/tmp/.ansible_tmp
verifier:
  name: ansible
