---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: oraclelinux
    image: oraclelinux:8
    pre_build_image: true
    command: "dnf install python3"
  - name: ubuntu-python
    image: ubuntu-python:latest
    dockerfile: Dockerfile
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
