---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    vector_service: 'vector.service'
  tasks:
  - name: Example assertion
    assert:
      that: true

  - name: 'Assert Vector Service'
    ansible.builtin.assert:
        that:
          - "'{{ vector_service }}' in ansible_facts.services"
          - "'running' == ansible_facts.services[vector_service].state"
          - "'enabled' == ansible_facts.services[vector_service].status"